### ISSUE TITLE
Create new module for Requests

### ISSUE THREAD

**Issue by babanesma** [camelcasetechsd/attendance-system#20]
create new module requests
This will hold the actions for creating new requests ( Epic 7 ) and listing requests the logged in user requests ( Epic 8 )
All actions in Epic 7 should be in this module

Create new module : requests 
Create 3 new controllers : Vacation , Permission & WorkFromHome
In each controller create one action till now : create

**Comment by babanesma** [comment]
@mohamed-ramdan there are a lot of unused files in your commit ( ending with ~ ) , I think these are the autosaved files from gedit 
I have already add this type of files to .gitignore , but you should remove them from the repo ( try to use git rm --cached <filename>~ ) 
Also avoid using git commit -a in the future

**Comment by babanesma** [comment]
@mohamed-ramdan there are some comments to mark it done 
- remove views/scripts/index , there is no index controller yet
- add a new drop down in the navigation menu for the new module 
- in each controller , remove the index action along with the index.phtml view file and add the create action

**Comment by mohamed-ramdan** [comment]
Done
