### ISSUE TITLE
[Vacation Request] Create form for adding new vacation request 

### ISSUE THREAD

**Issue by babanesma** [camelcasetechsd/attendance-system#22]
the user should be the logged in one 
if one day then user can select (casual, annual, or sick)
if more than a day then user can select ( annual or sick)
in case of sick a scanned certificate must be attached to the vacation request

**Comment by babanesma** [comment]
- populate the vacation type when loading the form 
- when selecting from date , this is only one day vacation , then user can select any type of vacation 
- when selecting to date which is bigger than from date , then user can select only sick or annual vacation 
- when selecting sick vacation , attachment field is shown , and user can attach sick certificate 
- make the attachment label along with the attachment input file field appear when it is sick vacation , right now the attachment label is shown when it is not required

**Comment by mohamed-ramdan** [comment]
./bin/cli orm:schema-tool:drop --force ; ./bin/cli orm:schema-tool:update --force ; ./bin/cli schema:data-generate
