### ISSUE TITLE
Install behat environment 

### ISSUE THREAD

**Issue by babanesma** [camelcasetechsd/attendance-system#52]
Read this article first on how integrate behat with ZF1
http://www.widecodes.com/0QJekkgVVk/zend-framework-integration-with-behat-bdd.html

Skip the part of behat installation via pear , only run git pull then composer update to install behat .

Create the features directory under the root directory of the application .
Follow the article until you run behat command ( run ./vendor/bin/behat ).

**Comment by ahmedReda1** [comment]
http://www.inanzzz.com/index.php/post/5rxn/taking-screenshots-of-failed-scenarios-in-behat3
