### ISSUE TITLE
[Notifications] Investigate in the notifications sections

### ISSUE THREAD

**Issue by babanesma** [camelcasetechsd/attendance-system#61]
- understand the current implemented work for handling the notifications 
  - login with normal user and create a request 
  - login with high level user and you should see a notifications on the right 
- investigate which library we can use to implement 
- Libraries suggested 
  - http://framework.zend.com/manual/1.12/en/zend.event-manager.event-manager.html
  - https://github.com/gplanchat/php-event-manager 
  - https://github.com/zendframework/zend-eventmanager

This part is copied from the specs document 

> The main objective of this task is to give the user/manager the ability to get notifications about events of the system in regard to his/her actions like
> - requests
> - exceeding number of vacations
> - lateness notifications

**Comment by lebaz20** [comment]
@babanesma I prepared the attached comparison version for notifications display ;

[#61 notifications comparison.pdf](https://github.com/camelcasetechsd/attendance-system/files/26161/61.notifications.comparison.pdf)
